# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-10 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readdetail',
            name='user',
        ),
    ]
