# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20181014_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauth_ex',
            old_name='qq_openid',
            new_name='openid',
        ),
    ]
