# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_auto_20181014_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth_ex',
            name='oauth_type',
        ),
        migrations.DeleteModel(
            name='OAuth_type',
        ),
    ]
