# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_auto_20181014_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth_ex',
            options={'verbose_name': '第三方', 'verbose_name_plural': '第三方'},
        ),
        migrations.AddField(
            model_name='oauth_ex',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='oauth_ex',
            name='oauth_type',
            field=models.CharField(choices=[('1', 'GitHub'), ('2', 'QQ'), ('3', 'WeiBo')], default='1', max_length=1, verbose_name='来源'),
        ),
    ]
