# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20181014_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth_ex',
            name='image_url',
            field=models.URLField(default='', verbose_name='头像地址'),
        ),
    ]
