# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-14 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_oauth_ex_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauth_ex',
            name='image_url',
        ),
    ]
